### ISSUE TITLE
use of laravel bi

### ISSUE THREAD

**Issue by kalpesh52** [laravel-bi/laravel-bi#21]
i want to give access to user to create custom dashboard according to his convenient, so how can we achieve it.
i had installed setup now please tell me how to check surf that dashboard  there is not route to access for it.
i had followed all steps as per you provided.
thanks in advance

**Comment by alberto-bottarini** [comment]
In config/bi.php you can setup your "bi dashboard prefix" (default is /bi).

You should see dashboards here: http://yourdomain/bi

**Comment by kalpesh52** [comment]
getting this
when access this http://localhost/lara-bi/public/bi 
403
This action is unauthorized.

**Comment by alberto-bottarini** [comment]
What about BiServiceProvider?

**Comment by support-immunityhealth** [comment]
i think that is cache problem 
change BI_PATH in config/bi.php   and run
php artisan config:cache
