### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by Messhias** [laravel-bi/laravel-bi#30]
Trying to install it in laravel 9.x

```
composer require laravel-bi/laravel-bi
Using version ^1.1 for laravel-bi/laravel-bi
./composer.json has been updated
Running composer update laravel-bi/laravel-bi
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel-bi/laravel-bi ^1.1 -> satisfiable by laravel-bi/laravel-bi[v1.1.0, v1.1.1, v1.1.2].
    - laravel-bi/laravel-bi[v1.1.0, ..., v1.1.2] require illuminate/support ^8.0 -> found illuminate/support[v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.27).

You can also try re-running composer require with an explicit version constraint, e.g. "composer require laravel-bi/laravel-bi:*" to figure out if any version is installable, or "composer require laravel-bi/laravel-bi:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by firextechnologies** [comment]
I have the same issue the best way to work around do the following 

create another folder 

and run the composer command 

once it's done go and copy the folders from the vendor folder to your-laravel-project/vendor

then do the following 

in the root folder of your laravel 
you will find the composer.json 
open it and add the following 

"laravel-bi/laravel-bi": "^1.1" to the "require": { } 
and open your-laravel-project/vendor/laravel-bi/laravel-bi/composer.json 
and update the following 
"illuminate/support": "^8.0"
to 
"illuminate/support": "^8.x-dev"

and it will work find even if you do 
composer dumpautoload 

i hope after all this the package will work as i need ^^ 

good luck

**Comment by Messhias** [comment]
Any updates on this?

**Comment by firextechnologies** [comment]
facing same issue, even though i manage to get it in vendor but still can`t make the artisan command work

**Comment by alberto-bottarini** [comment]
Tag 1.1.3 created, please use it
